@startuml "CTS Object Diagram"
/'**Легенда 
Обязательность заполнения реквизита (Mandatory):
    *                           Реквизит обязательный для заполненияТипы реквизита:

Типы данных (DataType):
    str:<long>                  Строка (string) определенной длинны в символах, размер лучше всего указывать кратным 8, т.е. 32, 64, 128, 256 и т.д., минимальная длина строки 32 символа.
    text                        Текст (text) неограниченно длинны.
    int                         Беззнаковое целое число (integer).
    float:<accuracy>            Число (numeric). Вещественное число с определенной точностью. Точность определяется количеством знаков после запятой в формате .<число знаковпосле запятой>.
    date:<mask>                 Дата (date). С помощью маски задается формат вводимого значения, dd, mm, yy, yyyy. Например: dd.mm.yyyy т.д.
    time:<mask>                 Время (time). С помощью маски задается формат вводимого значения, элементы маски hh, mm, ss. Пример: hh:mm:ss, hh:mm, mm:ss и т.д.
    datetime:<mask>             Дата и время (datetime). Дата, дата и время с определенной точностью. С помощью маски задается формат вводимого значения dd.mm.yyyy(yy)_hh:mm:ss, или dd.mm.yyyy(yy).
    bool                        Логический (boolean). Логическое значение - Истина/Лож. Используется для чек-боксов и радио-кнопок.
    enum                        Перечисление (enumeration). Значения перечисления указываются в следующей строке в <enumvalue:>, в виде комментария обозначаемом "'", через "," в формате <code>|<Name>. Перечисление, используется для полей с выпадающим списком к количеством значенией не более 5-10.
    bin                         Бинарный (binary) тип данных. Используется для указания на то что в поле будут хранится именно бинарные данные, например, такие как бинарный данные различных файлов и т.д.
    <ObjectName>:<choice_type>  Указывается имя объекта значение записи которго используется в качестве значения реквизита. Тип выбора - single (одно значение)/plural (несколько значений).

Заполнение реквзитов (Filling):
    manual                      Заполняется вручную.
    auto:create/save            Заполняется автоматически при создании/сохранении записи.
    generated:create/save       Генерируется автоматически при созранении/созранении записи.
    <value>                     Заполняется конкретным значеним по умолчанию при создании записи, например - true.
    develop                     Заполняется в процессе разработки ПО.

Отображение реквизита в интерфейсе (Visibility): 
    form                        Отображать в представлиении формы карточки экземпляра объекта.
    list                        Отображать в представлении реестра (списка) объектов.   
    Может быть  указано сразу оба значения через "&". 

Формат описания объектов (сущьностей):
    EntityName                  Имя объекта.
    EntityStage                 Состояние объекта, Work (в работе)/Ready (готово)    'Сущьности:

    /'Наименование объекта'/ entity EntityName <<EntityStage>> {
        /'Наименование реквизита'/<Mandatory>RequisiteName: DataType:argument Filling Visibility
    }
        
    'Пример:
    /'Пользователи'/ entity Users <<Work>> {
        *Id: int generated
        --
        /'Имя пользователя'/ *Name: str:32 manual form&list
        /'Пароль'/ *Password: str:32 manual form&list
        /'Группа'/ Group: Groups manual
    }
'/

'**Оформление объектов
skinparam class {
/'Готово'/      BackgroundColor<<Ready>>    LightGreen
/'В работе'/    BackgroundColor<<Work>>     LightYellow
}

'**Объекты

/'Классификатор товаров'/ entity  CommoditiesClassifier <<Work>> {
    *Id: GUID generated
    --
    /'Тип записи'/ *Type: enum:section|Отделение,category|Категория,kond|Вид form
    /'Уровень родитель'/ *ParentLevel: CommoditiesClassifier:single manual form&list
    /'Код'/ Code str:16 manual form&list
    /'Краткое наименование'/ ShortName: str:32 manual form&list
    /'Полное наименование'/ FullName: str:128 manual form&list
 }

/'Пользователи'/ entity Users <<Work>> {
    *Id: GUID generated
    --
    /'Имя пользователя'/ *Name: str:32 manual form&list
    /'Пароль'/ *Password: str:32 manual form&list
    /'???Группа'/ GroupId: Groups manual
    /'Организация'/ *OrganisationId: Organisations auto form
    /'Имя'/ *Name: str:64 manual form
    /'Отчество'/ MiddleName: str:64 manual form
    /'Фамилия'/ *LastName: str:64 manual form 
    /'Должность'/ *Position: str:64 manual form
    /'Телефон'/ *Phone: str:24 manual form
    /'Е-мэйл'/ *Email: str:32 manual form
    /'Действует на основании (устава/доверенности)'/ *ActionBasis: enum:01.Устава, 02.Доверенности
    /'ЭЦП'/ Signature: str
    /'Дата начала действия ЭЦП'/ SignatureDateStart: date manual form
    /'Дата окончания действия ЭЦП'/ SignatureDateEnd: date manual form
 }

/'Группы пользователей'/ entity Groups <<Work>> {
    *Id: GUID generated
    --
    /'Имя пользователя'/ *Name: str:32 manual form&list
    /'Группа'/ Group: Groups:single manual form
    /'Права'/ Permissions: Permissions:plural manual
 }

/'Разрешения'/ entity Permissionы <<Work>> {
    *Id: GUID generated
    --
    /''/ *
 }

/'???Операции'/ entity Operations <<Work>> {
    *Id: GUID generated
    --
    /''/ *
 }

/'Роли'/ entity Roles <<Work>> {
    *Id: GUID generated
    --
    /'Тип роли'/ *Type: enum:static.Статическая,calculate.Вычисляемая
    /'Пользователи'/ UsersId: Users/plural manual form
    /'Группы'/ GrroupId: Groups/plural manual form
    /'Вычисление'/ Calculation: text manual form
 }

/'Организации-участники торгов'/ entity Organizations <<Work>> {
    *Id: GUID generated
    --
    /'Код'/ *Code: str64 auto:create form&list 
    /'Код ЦБ'/*CodeCB: str64 manual  form&list
    /'!! Правила формирования Кода(прописать правила) Для Юр.лиц Код=ИНН; Для иностранных орг. Код= КИО; Для ИП Код= серия и номер паспорта'/
    /'Форма собственности'/ *OwnershipTypeId: OwnershipTypes:single manual form
    /'Полное наименование'/ *FullName: str:256 manual form&list
    /'Краткое наименование'/ *ShortName: str:128 manual form&list
    /'!!Только для ин.юр. лиц!! Полное наименование на иностранном языке'/ FullNameForeignLanguage: str:256 manual form&list
    /'!!Только для ин.юр. лиц!! Краткое наименование'/ ShortNameForeignLanguage: str:128 manual form&list
    /'Код страны'/*CountryId: Adresses:single manual form
    /'Юридический адрес'/ *LegalAddressId: Addresses:plural manual form
    /'Почтовый адрес'/ *PostalAddressId: Addresses:plural manual form
    /'ИНН'/ *INN-KIO: str:12 manual form
    /'КПП'/ *KPP: str:9 manual form
    /'ОКПО'/ *OKPO: str:12 manual form
    /'ОГРН'/ OGRN: int:single manual form
    /'Дата выдачи ОГРН'/ OGRNDate: date manual form
    /'Место выдачи ОГРН'/ OGRNPlace: str:256 manual form
    /'!!! Только для ИП!!! ОГРНИП'/ OGRNIP: int:single manual form
    /'!!! Только для ИП!!! Дата регистрации ИП'/ DateIP: date manual form
    /'Дата государственной регистрации физического лица в качестве ИП'/
    /'ФИО руководителя'/ *CEOFullName: str:256 manual form
    /'ФИО руководителя в родительном падеже'/ *CEOFullNameGenetive: str:256 manual form
    /'Должность руководителя'/ *CEOPostName: str:256 manual form
    /'Должность руководителя в родительном падеже'/ *CEOPostNameGenetive: str:256 manual form
    /'Телефон'/ *Phone: int:single manual form
    /'Факс'/ Fax: int:single manual form
    /'Е-мэйл'/ *Email: str:64 manual form
    /'Web-адрес'/ WebAddress: str:64 manual form
    /'??? Вид деятельности (Код ОКВЭД)'/ *BusinessLineId: BusinessesLine:plural manual form
    /'Наименование банка'/ *BankId: Banks:single manual form
    /'Расчетный счёт'/ *CheckingAccount: int manual form
    /'??? Аккредитация'/ *Accreditation: bool manual form
    /'???Дата аккредитации'/ AccreditationDate: date manual form
    /'???Дата отмены аккредитации'/ CancellationDate: date manual form
    

    --
    /'Статус'/ *Status: OrganizationStatuses:single auto:create form
    /'Создано'/ *CreatedAtDateTime: datetime:dd.mm.yyyy_hh:mm:ss auto:save form
    /'Автор'/ *CreatedByGuid: Users:single auto:create form&list
}

/'Адреса'/ entity Addresses <<Work>> {
    *Id: GUID generated
    --
    /'Тип записи'/ *Type: enum form
    'enumvalue: postcode|Индекс,country|Страна,region|Регион,city|Город,township|Поселок,village|Древня,street|Улица,bilding|Дом,housing|Корпус,room|Комната,station|Станция
    /'Уровень родитель'/ *ParentLevelId: Addresses:single manual form&list
    /'Код'/ Code int manual form&list
    /'Краткое наименование'/ ShortName: str:32 manual form&list
    /'Полное наименование'/ FullName: str:128 manual form&list
    /'Номер'/ Number int manual form&list
    --
    /'Создано'/ *CreatedAtDateTime: datetime:dd.mm.yyyy_hh:mm:ss auto:save form
    /'Автор'/ *CreatedByGuid: Users:single auto:create form&list
}



/'Формы собственности'/  entity OwnershipTypes <<Work>> {
    *Id: GUID generated create
    --
    /'Полное наименование'/ *FullName: str:256 manual form&list
    /'Краткое наименование'/ *ShortName: str:128 manual form&list
    --
    /'Создано'/ *CreatedAtDateTime: datetime:dd.mm.yyyy_hh:mm:ss auto:save form
    /'Автор'/ *CreatedByGuid: Users:single auto:create form&list
} 

/'Виды деятельности'/ entity BusinessesLine <<Work>> {
    *Id: GUID generated create
    --
    /'Код'/ *Code: float manual form
    /'Наименование'/ *Name: str:128 manual form
    /'Расшифровка'/ *Description: text manual form
    --
    /'Создано'/ *CreatedAtDateTime: datetime:dd.mm.yyyy_hh:mm:ss auto:save form
    /'Автор'/ *CreatedByGuid: Users:single auto:create form&list
}

/'Банки'/ entity Banks <<Work>> {
    *Id: GUID generated create
    --
    /'Полное наименование'/ *FullName: str:250 manual form
    /'Краткое наименование'/ *ShortName: str:250 manual form
    /'БИК'/ *BIK: int: single manual form
    /'Адрес'/ *AddressId: Addresses:plural manual form
    /'Корресподентский счёт'/ *CorrespondentAccount: int:single manual form
    /'Телефон'/ *Phone: str 50:single manual form
    /'E-мэйл'/ *Email: str:50 manual form
    --
    /'Создано'/ *CreatedAtDateTime: datetime:dd.mm.yyyy_hh:mm:ss auto:save form
    /'Автор'/ *CreatedByGuid: Users:single auto:create form&list
}

/'Статус организации'/ entity OrganizationStatuses <<Work>> {
    *Id: GUID generated create
    --
    /'Название'/ *Name: str:32 manual form
    /'Описание'/ Description: text:single manual form
}

/'Документы'/ entity Documents <<Work>> {
    *Id: GUID generated create
    --
    /'Название Документа'/ *Name: str:128 auto form&list
    /'Указать принцип формирования наименования'/
    /'Вид документа'/ *DocumentKindId: DocumentKinds:single manual form 
    /'Тип карточки документы'/ *DocumentTypeId: DocumentTypes:single auto:creatre form 
    
    --
    /'Создано'/ *CreatedAtDateTime: datetime:dd.mm.yyyy_hh:mm:ss auto:save form
    /'Автор'/ *CreatedByGuid: Users:single auto:create form&list
    
}

/'Вид документа'/ entity DocumentKinds <<Work>>{
    *Id: GUID generated create
    --
    /'Код'/ *Code: str:12 manual form
    /'Наименование'/  *Name: str:64 manual form
    /'Описание'/ Description: text manual form
    --
    /'Создано'/ *CreatedAtDateTime: datetime:dd.mm.yyyy_hh:mm:ss auto:save form
    /'Автор'/ *CreatedByGuid: Users:single auto:create form&list
}

/'Тип карточки документа'/ entity DocumentTypes <<Work>>{
    *Id: GUID generated create
    --
    /'Код'/ *Code: str:12 manual form
    /'Наименование'/  *Name: str:64 manual form
    /'Описание'/ Description: text manual form
    /'Перечень реквизитов типа карточки'/ *DocTypesRequisites: enum:<DocTypesFieldsNames,...> develop
    --
    /'Создано'/ *CreatedAtDateTime: datetime:dd.mm.yyyy_hh:mm:ss auto:save form
    /'Автор'/ *CreatedByGuid: Users:single auto:create form&list
}


/'???Личный кабинет'/ entity Room <<Work>> {
    *Id: GUID generated <FK>
    --
    /'Организация'/ *Organization: Organisations:single auto:create

}

'**Связи объектов

'Пользователи
Users::Organisation }|--|| Organizations::Id
Users::Groups }|--||Groups::Id
Users::Roles }|--|| Roles::Id

'Организация
Organizations::Documents }|--||Documents::Id
Organizations::OwnershipTypes ||--|{ OwnershipTypes::Id
Organizations::BusinessesLine }|--|{ BusinessesLine::Id
Organizations::Addresses ||--|{ Addresses::Id
Organizations::Banks ||--|{ Banks::Id
Organizations::OrganizationStatuses ||--|{ OrganzsationStatuses::Id

'Документация
Documents::DocumentKinds }|--|| DocumentKinds::Id
Documents::DocumentTypes }|--|| DocumentTypes::Id




@enduml