@startuml "ЦТС.А2.1"
/'Название файла будет: ЦТС.<Номер схемы БП>.<Номер этапа>.<Название этапа в схеме БП>'/
title "ЦТС.А2.1.1.Ввод данных для предварительной регистрации"
actor "Участник Торгов" as User
boundary "Форма для предворительной регистрации" as A
entity "База данных" as B
participant  "Кталог УТ" as C

autonumber
activate User
User -> A: Ввести данные ФИО, Корп. e-mai, Телефон, ИНН, Пароль, Подтв. пароля
activate A

A -> A: Проверка корректно заполненных данных
activate A
deactivate A

A --> User: Ошибка! Неправильные введены данные! Не заполнены обязательные поля
activate User
User-->A: Корректировка ранее введенных данных
deactivate User
A -> B: Сохранение данных в базе данных
activate B
B->B:создание записи в базе данных

A->C: создание записи в Каталоге УТ
activate C

@enduml


