@startuml 
/'Название файла будет: ЦТС.<Номер схемы БП>.<Номер этапа>.<Название этапа в схеме БП>'/
title "ЦТС.А2.1.1.Ввод данных для предварительной регистрации"
actor "Участник Торгов" as User
boundary "Форма для предворительной регистрации" as A
entity "База данных" as B
participant  "Каталог УТ" as C
participant "Профиль УТ" as D


autonumber

User -> A: Открыть форму
activate User
activate A
A-->User: Система показывает форму регистрации
deactivate User
deactivate A

loop Проверка и заполнение формы
User -> A: Ввести данные ФИО, Корп. e-mai, Телефон, ИНН, Пароль, Подтв. пароля
activate User
activate A
User -> A: Нажать кнопку "Сохранить" (Сохранить введенные данные)

A -> A: Проверка корректности заполненных данных 
activate A
deactivate User
A --> User: Ошибка! Неправильны введены данные! Не заполнены обязательные поля
deactivate A
activate User
User->A: Корректировка ранее введенных данных
deactivate User
deactivate A
end

A -> B: Сохранение данных в базе данных
activate A
activate B

B->B:Создание записи в базе данных

A->C: Создание записи в Каталоге УТ
deactivate B
deactivate A
activate C

C->User: Уведомление об успешном создании записи в Каталоге УТ
activate User
deactivate C

A ->D: Создание записи в Профиле УТ
activate D

D->A: Уведомление об успешном создание Пользователя
deactivate D

@enduml