/'v1 Схемы'/

' @startuml "Перечень биржевых товаров в спецификации"
' actor  "Участник торгов" as Foo0
' participant "Номер" as Foo1
' participant "Дата" as Foo2
' collections "Перечень берживых товаров" as Foo3
' participant "Сохранить" as Foo4
' participant "Наименование товара" as Foo6
' participant "Краткое название" as Foo7
' participant "Виды сопроводительных документов" as Foo8
' participant "Вид товара" as Foo13
' participant "Классификатор товаров" as Foo9
' participant "Лот единица измерения товара" as Foo10
' participant "Размер лота" as Foo11
' participant "Описание товара" as Foo12
' participant "Сохранить" as Foo13
' database "БД" as Foo5

' Foo0 -> Foo1: Выбрать товар из справочника
' Foo0 -> Foo2: Заполнение поля
' Foo0 -> Foo3: Заполнение табличной части

' group Перечень биржевых товаров в спецификации [Табличной части]
'     Foo0 -> Foo6 : Log attack end
'         group Новый товар [Запрос на добавление нового товара]
'             Foo0 -> Foo0: Товара нет в каталоге нименований товаров(Запрос на добавлнения нового товара)
'         end
'     Foo0 -> Foo7 : Заполнение поля
'     Foo0 --> Foo8 : Указать вид документа(Виды сопроводительных документов)
'     Foo0 -> Foo13 : Выбрать вид товара
'     Foo0 -> Foo9 : Указать класификатор
'     Foo0 -> Foo10 : Указать единица измерения товара
'     Foo0 --> Foo11 : Указать размер лота
'     Foo0 --> Foo12 : Добавить доп.описание товара
'     Foo13 -> Foo13: Записаь в Перечень биржевых товаров в спецификации
' end

' Foo0 <-- Foo3: Перечень биржевых товаров не заполнено
' Foo0 -> Foo4: Нажать Сохранить (Создать)
' Foo4 -> Foo5: Сохранения в БД
' @enduml

/'v2 Схема'/
@startuml "ЦТС.А3.1 Допуск товара к торгам"
/'Название файла будет: ЦТС.<Номер схемы БП>.<Номер этапа>.<Название этапа в схеме БП>'/
title "ЦТС.А3.1.2. Создания Спецификация на допуск товара к торгам"
actor "Участник Торгов" as User
boundary "Форма Спецификации биржевых товаров" as Specifications
collections "Форма Перечень биржевых товаров" as SpecificationCommodities
boundary "Форма на добавления товара в Каталог наименования товара" as CommoditiesNames
database "База данных" as Database
actor "Администратор Торгов" as User_CTS

autonumber
activate User
User -> Specifications: Ввести данные Номер, Дата, Перечень берживых товаров
note right
    manual: Номер, Дата,
    Перечень берживых товаров (табличная часть);
    auto: Статус, Дата создания, Автор.
end note
/'Форма Спецификации биржевых товаров'/
activate Specifications
Specifications -> SpecificationCommodities : Ввести данные Номер, Дата, Перечень берживых товаров
note right
    manual: Наименование товара, 
    Виды сопроводительных документов,
    Вид товара, Классификатор товаров, 
    Лот (единица измерения товара),
    Размер лота, Описание товара.
end note
/'Перечень биржевых товаров'/
activate SpecificationCommodities
SpecificationCommodities --> CommoditiesNames: Проверка корректно заполненных данных
    /'Форма на добавления товара в Каталог наименования товара'/
    activate CommoditiesNames
    /'Проверка корректно заполненных данных Каталог наименования товара->Участник Торгов'/
    CommoditiesNames -> CommoditiesNames: Проверка корректно заполненных данных
    activate CommoditiesNames
    deactivate CommoditiesNames
    CommoditiesNames --> User: Ошибка! Неправильные введены данные! Не заполнены обязательные поля
    activate User
    /'Ошибка и т.д. в Каталог наименования товара->Участник Торгов'/
    User-->CommoditiesNames: Корректировка ранее введенных данных
    deactivate User 
    CommoditiesNames->Database: Сохранение данных в базе данных
    activate Database
        Database->User_CTS: Запросы на добавления товара в Каталог наименования товара 
        /'Администратор Торгов'/
        activate User_CTS
        User_CTS->User_CTS: Проверка корректно заполненных данных, Утверждения 
        activate User_CTS
        User_CTS->User_CTS: Утверждения, Отказ
        User_CTS-->User: Причина отказа
        deactivate User_CTS
        User_CTS->Database: Сохранение данных в базе данных
        deactivate Database
        User_CTS-->CommoditiesNames: Cоздание записи в Каталоге наименования товара
        deactivate User_CTS
    deactivate CommoditiesNames
/'Ошибка и т.д. в Каталог наименования товара->Спецификации биржевых товаров'/
SpecificationCommodities -> SpecificationCommodities: Проверка корректно заполненных данных
activate SpecificationCommodities
deactivate SpecificationCommodities
/'Проверка корректно заполненных данных Спецификации биржевых товаров->Участник Торгов'/
Specifications -> Specifications: Проверка корректно заполненных данных
activate Specifications
deactivate Specifications
/'Ошибка и т.д. в Перечень биржевых товаров->Участник Торгов'/
SpecificationCommodities --> User: Ошибка! Неправильные введены данные! Не заполнены обязательные поля
activate User
/'Корректировка ранее введенных данных Участник Торгов->Спецификации биржевых товаров'/
User-->SpecificationCommodities: Корректировка ранее введенных данных
deactivate User
deactivate SpecificationCommodities
/'Ошибка и т.д. в Спецификации биржевых товаров->Участник Торгов'/
Specifications --> User: Ошибка! Неправильные введены данные! Не заполнены обязательные поля
activate User
/'Корректировка ранее введенных данных Участник Торгов->Спецификации биржевых товаров'/
User-->Specifications: Корректировка ранее введенных данных
deactivate User
/'Cоздание записи в Спецификации биржевых товаров'/
Specifications->Specifications: Cоздание записи в Спецификации биржевых товаров
activate Specifications
deactivate Specifications
/'Сохранение данных в базе данных'/
Specifications ->Database: Сохранение данных в базе данных
activate Database
deactivate Database
@enduml