@startuml
title "ЦТС. А2.1.4.Автоматическая проверка"

boundary "Система" as A
entity "База данных" as B
Control "Внешняя ИС" as C
actor "Менеджер клиентского сервиса" as CustomerServiceManager
actor "Участник Торгов" as User

autonumber

activate A
A->A: Формирует список данных для автоматической проверки 

A->B: Вытягивание нужных данных из БД
activate B
B->A: Передача данных в систему
deactivate B

A->C: Запрос во внешнюю ИС для проверки данных
activate A
activate C

C->A: Отправка необходимых данных в Систему
A->A:Проверка данных
activate A
deactivate A
deactivate C

/'Если проверка не пройдена'/
A->A: Формирование списка данных для ручной проверки
A->CustomerServiceManager:Уведомление о не пройденной проверки.
activate CustomerServiceManager
deactivate CustomerServiceManager
A->User:Уведомление о не пройденной проверки
activate User
deactivate User

/'Если проверка пройдена'/
A->User:Уведомление о пройденной проверки
activate User

@enduml