@startuml "CTS Object Diagram"
/'**Легенда 

Типы данных (DataType):
    str:<long>                  Строка (string) определенной длинны в символах, размер лучше всего указывать кратным 8, т.е. 32, 64, 128, 256 и т.д., минимальная длина строки 32 символа.
    text                        Текст (text) неограниченно длинны.
    int                         Беззнаковое целое число (integer).
    float:<accuracy>            Число (numeric). Вещественное число с определенной точностью. Точность определяется количеством знаков после запятой в формате .<число знаковпосле запятой>.
    date:<mask>                 Дата (date). С помощью маски задается формат вводимого значения, dd, mm, yy, yyyy. Например: dd.mm.yyyy т.д.
    time:<mask>                 Время (time). С помощью маски задается формат вводимого значения, элементы маски hh, mm, ss. Пример: hh:mm:ss, hh:mm, mm:ss и т.д.
    datetime:<mask>             Дата и время (datetime). Дата, дата и время с определенной точностью. С помощью маски задается формат вводимого значения dd.mm.yyyy(yy)_hh:mm:ss, или dd.mm.yyyy(yy).
    bool                        Логический (boolean). Логическое значение - Истина/Лож. Используется для чек-боксов и радио-кнопок.
    enum:enumvalue              Перечисление (enumeration). Значения перечисления указываются в следующей строке в <enumvalue:>, в виде комментария обозначаемом "'", через "," в формате enumvalue:<Id>|<Name>. Перечисление, используется для полей с выпадающим списком к количеством значенией не более 5-10.
    bin                         Бинарный (binary) тип данных. Используется для указания на то что в поле будут хранится именно бинарные данные, например, хэши и т.д.
    GUID                        Глобальный уникльный идентификатор.  

Формат описания объектов (сущьностей):
    EntityName                  Имя объекта.
    EntityStage                 Состояние объекта, Work (в работе)/Ready (готово).
    DataType:argument           Тип данных и даполнительный аргумент, напимер длина строки для строкового реквизита.
    RefrerenceObject.Requsite   Указание на то что данные в рекыизит нужно взять из реквизита указанного объекта, указывается при необходимости.     
    Mandatory                   Знаком "*" - реквизит обязательный для заполнения.

    /'Наименование объекта'/ entity EntityName <<EntityStage>> {
        /'Наименование реквизита'/<Mandatory>RequisiteName: DataType:argument:RefrerenceObject.Requsite
    }        
'/


'**Оформление объектов
skinparam class {
/'Готово'/      BackgroundColor<<Ready>>    LightGreen
/'В работе'/    BackgroundColor<<Work>>     LightYellow
}

'**Таблицы

/'Пользователи'/ entity Users <<Ready>> {
    *Id: GUID
    /'Организация'/ *OrganizationId: GUID:Organizations.Id
    /'Роль'/ *RoleId: GUID:Roles.Id
    --
    /'Логин'/ *Login: str:50
    /'Пароль'/ *Password: str:50
    /'Имя'/ *Name: str:50
    /'Отчество'/ MiddleName: str:50
    /'Фамилия'/ *LastName: str:50
    /'ФИО'/ FullName: str:200:Users.LastName&Name&MiddleName auto:save
    /'Должность'/ *Position: str:50
    /'Телефон'/ *Phone: str:50
    /'Е-мэйл'/ *Email: str:50
    /'Действует на основании)'/ *ActionBasis: enum:enumvalue
    'enumvalue:0|Устава, 1|Доверенности
    /'ЭЦП'/ Signature: str:50
    /'Дата начала действия ЭЦП'/ SignValidStartDate DateTime
    /'Дата окончания действия ЭЦП'/ SignValidEndDate DateTime
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Модифицировано'/ LastModifiedAt: DateTime
}

/'Роли'/ entity Roles <<Ready>> {
    *Id: GUID
    --
    /'Имя'/ *Name: str:50
    /'Описание'/ Description: str:500
     --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Разрешения'/ entity Permissions <<Work>> {
'?Нужно продумать как будем описывать разрешения для отдельных объектов?
    *Id: GUID
    --
    /'Имя'/ *Name: str:50
    /'Описание'/ Description str:500
    /'Роль'/ *RoleId: GUID:Roles.Id
     --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Адреса'/ entity Addresses <<Ready>> {
    *Id: GUID
    --
    /'Страна'/ *CountryId: GUID:Countries.Id
    /'Страна'/ *CountryName: str:200:Countries.Name
    /'Регион'/ *RegionId: GUID:Regions.Id
    /'Регион'/ *RegionName: str:200:Regions.Name
    /'Район'/ DistrictId: GUID:Districts.Id
    /'Район'/ DistrictName: str:200:Districts.Name
    /'Населенный пункт'/ LocalityId: GUID:Localities.Id
    /'Населенный пункт'/ LocalityName: str:200:Localities.Name
    /'Улица'/ Street: str:50
    /'Дом'/ Bilding: int
    /'Корпус'/ BildingPart: int
    /'Комната'/ Room: str:int
    /'Индекс'/ Postcode: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Страны'/ entity Countries <<Ready>> {
    *Id: GUID
    --
    /'Код'/ *CodeISO: int
    /'Наименование'/ *Name: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Регионы'/ entity Regions <<Ready>> {
    *Id: GUID
    --
    /'Страна'/ *СountyId: GUID:Countries.Id
    /'Код'/ Code: int
    /'Наименование'/ *Name: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Районы'/ entity Districts <<Ready>> {
    *Id: GUID
    --
    /'Регион'/ *RegionId: GUID:Regions.Id
    /'Наименование'/ *Name: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Населенные пункты'/ entity Localities <<Ready>> {
    *Id: GUID
    --
    /'Регион'/ *RegionId: GUID:Regions.Id
    /'Район'/ DistrictId: GUID:Districts.Id
    /'Наименование'/ *Name: str:200
    /'Типы населенных пунктов'/ LocalitiesTypes: enum:enumvalue
    'enumvalue: 0|Индекс,10|Город,20|Поселок,21|Станица,30|Древня,31|Село,32|Хутор,40|Станция,41|ЖД станция
     --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Организации-участники торгов'/ entity Organizations <<Work>> {
    *Id: GUID
    --
    /'Код'/ *Code: str:50
    /'Код ЦБ'/*CodeCB: str:50
    /'Форма собственности'/ *OwnershipTypeId: GUID:OwnershipTypes.Id 
    /'Наименование'/ *Name: str:200
    /'Сокращенно наименование'/ *ShortName: str:50
    /'Полное наименование на иностранном языке'/ ForeignLanguageName: str:200
    /'Краткое наименование на иностранном языке'/ ForeignLanguageShortName: str:50
    /'Страна'/*CountryId: GUID:Countries.Id
    /'Страна'/ *CountryName: str:200:Countries.Name
    /'Юридический адрес'/ *LegalAddressId: GUID:Addresses.Id
    /'Почтовый адрес'/ *PostalAddressId: GUID:Addresses.Id
    /'ИНН'/ INN: str:50
    /'КИО'/ KIO: str:50
    /'КПП'/ KPP: str:50
    /'ОКПО'/ OKPO: str:50
    /'ОГРН'/ OGRN: str:50
    /'Дата присвоения ОГРН'/ OGRNDate: date
    /'Место выдачи ОГРН'/ OGRNPlace: str:200
    /'ОГРНИП'/ OGRNIP: str:50
    /'Дата регистрации ИП'/ OGRNIPDate: date
    /'Паспорт'/ Passport:str50
    /'ФИО руководителя'/ *CEOFullName: str:200
    /'ФИО руководителя в родительном падеже'/ *CEOFullNameGenetive: str:200
    /'Должность руководителя'/ *CEOPostName: str:200
    /'Должность руководителя в родительном падеже'/ *CEOPostNameGenetive: str:200
    /'Телефон'/ *Phone: str:50
    /'Е-мэйл'/ *Email: str:50
    /'Web-адрес'/ URL: str:50
    /'Вид деятельности по ОКВЭД'/ *OKVEDId: GUID:OKVED.Id
    /'Банк'/ *BankId: GUID:Banks.Id
    /'Расчетный счёт'/ *CheckingAccount: str:50
    /'Дата аккредитации'/ AccreditationDate: date 
    /'Дата отмены аккредитации'/ CancellationDate: date 
    --
    /'Статус'/ *StatusId: GUID:OrganizationStatuses.Id
    /'Дата статуса'/ *StatusDate: Date
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Статус организации'/ entity OrganizationStatuses <<Ready>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Формы собственности'/  entity OwnershipTypes <<Ready>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
} 

/'Банки'/ entity Banks <<Ready>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:200
    /'БИК'/ *BIK: str:50
    /'Адрес'/ *AddressId: GUID:Addresses.Id
    /'Корресподентский счёт'/ *CorrespondentAccount: str:50
    /'Телефон'/ *Phone: str:50
    /'Веб-адрес'/ URL: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Виды деятельности по ОКВЭД'/ entity OKVED <<Ready>> {
    *Id: GUID generated create
    --
    /'Код'/ *Code: str:50
    /'Код-родитель'/ *OKVEDId: GUID:OKVED.Id
    /'Наименование'/ *Name: str:200
    /'Расшифровка'/ *Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Документы'/ entity Documents <<Ready>> {
    *Id: GUID generated create
    --
    /'Организация'/ *OrganizationId: GUID:Organizations.Id
    /'Вид документа'/ *DocumentKindId: GUID:DocumentKinds.Id 
    /'Наименование документа'/ *Name: str:200
    /'Номер документа'/ *Name: str:50
    /'Дата документа'/ *Date: Date
    /'Тема документа'/ *Name: str:200
    /'Дата завердения действия'/ EndDate: Date
    --
    /'Сыылка на документ в файловом зранилище'/ *FileId: GUID
    /'Расширение файла'/ FileExtention str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Связи Документов'/ entity DocumentLinks <<Ready>> {
    *Id: GUID generated create
    --
    /'Документ'/ *OrganizationId: GUID:Organizations.Id
    /'Вид объекта'/ *DocumentKindId: GUID:...
    /'Объект'/ *ObjectID: GUID:...
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}


/'Вид документа'/ entity DocumentKinds <<Ready>>{
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Каталог товаров, работ и услуг (ТРУ)'/  entity Commodities <<Work>> { 
    *Id: GUID
    /'Классификатор товаров'/ *CommoditiesClassifierId: GUID:CommoditiesClassifier.Id
    /'Спецификация'/ *SpecificationId: GUID:Specifications.Id
    /'Продавец'/ OrganisationId: GUID:Organisations.Id
    --
    /'Наименование'/ *NameId: GUID:CommoditiesNames.Id
    /'Мнемоника'/ *Mnemonic: str:50
    /'Лот (единица измерения товара)'/ *BaseUnitId: GUID:BaseUnits.Id
    /'Размер лота'/ Quantity: float: 
    /'Базис поставки'/ *DeliveryBasisId: GUID:Addresses.Id
    /'Завод-производитель'/ *CommodityManufacturerId: GUID:CommodityManufacturers.Id
    /'Упаковка'/ *PackageKindId: GUID:PackageKinds.Id
    /'Описание'/ Description: str:200
    --
    /'Статус'/ *StatusId: GUID:CommodityStatuses.Id
    /'Дата статуса'/ *StatusDate: Date
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Наименования товаров'/ entity CommoditiesNames <<Work>> {
    *Id: GUID
    /'Классификатор товаров'/ *CommoditiesClassifier: GUID:CommoditiesClassifier.Id
    --
    /'Наименование'/ *Name: str:200
    /'Краткое наименование'/ *ShortName: str:50
    --
    /'Статус'/ *StatusId: GUID:CommodityStatuses.Id
    /'Дата статуса'/ *StatuseDate: Date
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Спецификации биржевых товаров'/ entity CommoditySpecifications <<Work>> {
    *Id: GUID
    --
    /'Номер'/ *Number: str:50
    /'Дата'/ *Date: Date
    /'Тип спецификации'/ *SpecificationType: enum:enumvalue
    'enumvalue:1|На допуск товара,2|На корректировку товара, 3|На снятие товара
    /'Участник торгов'/ *OrganisationId: GUID:Organisations.Id
    --
    /'Статус'/ *StatusId: GUID:SpecificationStatuses.Id
    /'Дата статуса'/ *StatusDate: Date
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Табличная часть Спецификаций биржевых товаров'/ entity CommoditySpecificationTables <<Work>>{
    *Id: GUID 
    /'Спецификация'/ *CommoditySpecifications: GUID:CommoditySpecifications.Id
    --
    /'Наименование товара'/ *CommodityNameId: GUID:CommoditiesNames.Id
    /'Мнемоника'/ *Mnemonic: str:50
    /'Единица измерения)'/ *MeasuringUnitsId: GUID:BaseUnit.Id
    /'Размер лота'/ *Quantity: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

'**Справочники

/'Статусы Каталога ТРУ'/ entity CommodityStatuses <<Work>>{
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Статусы Cпецификации'/ entity SpecificationStatuses <<Work>>{
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Единицы измерения'/ entity MeasuringUnits <<Work>> {
    *Id: GUID
    --
    /'Ннаименование'/ *Name: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Заводы-производители'/ entity CommodityManufacturers <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str: 200
    /'Краткое наименование'/ *ShortName: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Виды упаковок'/ entity PackageKinds <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Классификатор товаров'/ entity CommoditiesClassifier <<Ready>> {
    *Id: GUID
    --
    /'Отделение торгов'/ CommoditySectionId: GUID:CommoditySections.Id
    /'Категория товаров'/ CommodityCategoryId: GUID:CommodityCategories.Id
    /'Виды товаров'/ CommodityKindId: GUID:CommodityKinds.Id
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Отделения торгов'/ entity CommoditySections<<Ready>> {
    *Id: GUID
    --
    /'Код'/ Code str:50
    /'Полное наименование'/ Name: str:200
    /'Краткое наименование'/ ShortName: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Категории товаров'/ entity CommodityCategories <<Ready>> {
    *Id: GUID
    --
    /'Код'/ Code str:50
    /'Отделение торгов'/ CommodityDeskId: GUID:CommodityDesks.Id
    /'Полное наименование'/ Name: str:200
    /'Краткое наименование'/ ShortName: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

/'Виды товаров'/ entity CommodityKinds <<Ready>> {
    *Id: GUID
    --
    /'Код'/ Code str:50
    /'Категория товаров'/ CommodityCategoryId: GUID:CommodityCategories.Id
    /'Полное наименование'/ Name: str:200
    /'Краткое наименование'/ ShortName: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedById: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedById: GUID:Users.Id
}

'***Связи таблиц

'Пользователи
    Users::OrganizationId }|--|| Organizations::Id
    Users::RolesId }|--|| Roles::Id
    
'Разрешения'
    Permissions::RolesId }|--|{ Roles::Id

'Адреса
    Addresses::CountryId }|--|| Countries::Id
    Addresses::RegionId }|--|| Regions::Id
    Addresses::DistrictId }|--|| Districts::Id
    Addresses::LocalityId }|--|| Localities::Id

'Организация
    Organizations::OwnershipTypeId }|--|| OwnershipTypes::Id
    Organizations::OKVEDId }|--|| OKVED::Id
    Organizations::PostalAddressId }|--|| Addresses::Id
    Organizations::BankId }|--|| Banks::Id
    Organizations::StatusId }|--|| OrganizationStatuses::Id

'Документы
    Documents::OrganizationId }|--|| Organizations::Id
    Documents::DocumentKindsId }|--|| DocumentKinds::Id

/'New 09/12/21'/
'Каталог ТРУ'
    Commodities::NameId ||--|| CommoditiesNames::Id
    Commodities::MeasuringUnitId }|--|| MeasuringUnits::Id
    Commodities::CommoditiesClassifier }|--|| CommoditiesClassifier::Id
    Commodities::PackageKindId ||--|| PackageKinds::Id
    Commodities::CommodityManufacturerId }|--|| CommodityManufacturers::Id
    Commodities::OrganisationsId }|--|| Organizations::Id
    Commodities::StatusId }|--|| CommodityStatuses::Id
    Commodities::CommoditySpecificationId ||--|| CommoditySpecifications::Id 

'Спецификация биржевых товаров
    CommoditySpecifications::OrganisationId }|--|| Organizations::Id
    CommoditySpecifications::StatusId }|--|| SpecificationStatuses::Id

'Табличная часть Спецификаций биржевых товаров
    CommoditySpecificationTables::CommoditySpecificationId }|--|| CommoditySpecifications::Id
    CommoditySpecificationTables::CommodityNameId }|--|| CommoditiesNames::Id
    CommoditySpecificationTables::MeasuringUnitId }|--|| MeasuringUnits::Id

@enduml