@startuml "CTS Object Diagram"
/'**Легенда 

Типы данных (DataType):
    str:<long>                  Строка (string) определенной длинны в символах, размер лучше всего указывать кратным 8, т.е. 32, 64, 128, 256 и т.д., минимальная длина строки 32 символа.
    text                        Текст (text) неограниченно длинны.
    int                         Беззнаковое целое число (integer).
    float:<accuracy>            Число (numeric). Вещественное число с определенной точностью. Точность определяется количеством знаков после запятой в формате .<число знаковпосле запятой>.
    date:<mask>                 Дата (date). С помощью маски задается формат вводимого значения, dd, mm, yy, yyyy. Например: dd.mm.yyyy т.д.
    time:<mask>                 Время (time). С помощью маски задается формат вводимого значения, элементы маски hh, mm, ss. Пример: hh:mm:ss, hh:mm, mm:ss и т.д.
    datetime:<mask>             Дата и время (datetime). Дата, дата и время с определенной точностью. С помощью маски задается формат вводимого значения dd.mm.yyyy(yy)_hh:mm:ss, или dd.mm.yyyy(yy).
    bool                        Логический (boolean). Логическое значение - Истина/Лож. Используется для чек-боксов и радио-кнопок.
    enum:enumvalue              Перечисление (enumeration). Значения перечисления указываются в следующей строке в <enumvalue:>, в виде комментария обозначаемом "'", через "," в формате enumvalue:<Id>|<Name>. Перечисление, используется для полей с выпадающим списком к количеством значенией не более 5-10.
    bin                         Бинарный (binary) тип данных. Используется для указания на то что в поле будут хранится именно бинарные данные, например, хэши и т.д.
    GUID                        Глобальный уникльный идентификатор.  

Формат описания объектов (сущьностей):
    EntityName                  Имя объекта.
    EntityStage                 Состояние объекта, Work (в работе)/Ready (готово).
    DataType:argument           Тип данных и даполнительный аргумент, напимер длина строки для строкового реквизита.
    RefrerenceObject.Requsite   Указание на то что данные в рекыизит нужно взять из реквизита указанного объекта, указывается при необходимости.     
    Mandatory                   Знаком "*" - реквизит обязательный для заполнения.

    /'Наименование объекта'/ entity EntityName <<EntityStage>> {
        /'Наименование реквизита'/<Mandatory>RequisiteName: DataType:argument:RefrerenceObject.Requsite
    }        
'/


'**Оформление объектов
skinparam class {
/'Готово'/      BackgroundColor<<Ready>>    LightGreen
/'В работе'/    BackgroundColor<<Work>>     LightYellow
}

'**Таблицы

/'Пользователи'/ entity Users <<Ready>> {
    *Id: GUID
    --
    /'Логин'/ *Login: str:50
    /'Пароль'/ *Password: str:50
    /'Роль'/ RoleId: GUID:Roles.Id
    /'Организация'/ *OrganizationId: GUID:Organizations.Id
    /'Имя'/ *Name: str:50
    /'Отчество'/ MiddleName: str:50
    /'Фамилия'/ *LastName: str:50
    /'ФИО'/ FullName: str:200:Users.LastName&Name&MiddleName auto:save
    /'Должность'/ *Position: str:50
    /'Телефон'/ *Phone: str:50
    /'Е-мэйл'/ *Email: str:50
    /'Действует на основании)'/ *ActionBasis: enum:enumvalue
    'enumvalue:0|Устава, 1|Доверенности
    /'ЭЦП'/ Signature: str:50
    /'Дата начала действия ЭЦП'/ SignValidStartDate DateTime
    /'Дата окончания действия ЭЦП'/ SignValidEndDate DateTime
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Модифицировано'/ LastModifiedAt: DateTime
}

/'Роли'/ entity Roles <<Ready>> {
    *Id: GUID
    --
    /'Имя'/ *Name: str:50
    /'Описание'/ Description: str:500
     --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Разрешения'/ entity Permissions <<Work>> {
'?Нужно продумать как будем описывать разрешения для отдельных объектов?
    *Id: GUID
    --
    /'Имя'/ *Name: str:50
    /'Описание'/ Description str:500
    /'Роль'/ *RoleId: GUID:Roles.Id
     --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Адреса'/ entity Addresses <<Ready>> {
    *Id: GUID
    --
    /'Страна'/ *CountryId: GUID:Countries.Id
    /'Страна'/ *CountryName: str:200:Countries.Name
    /'Регион'/ *RegionId: GUID:Regions.Id
    /'Регион'/ *RegionName: str:200:Regions.Name
    /'Район'/ DistrictId: GUID:Districts.Id
    /'Район'/ DistrictName: str:200:Districts.Name
    /'Населенный пункт'/ LocalityId: GUID:Localities.Id
    /'Населенный пункт'/ LocalityName: str:200:Localities.Name
    /'Улица'/ Street: str:50
    /'Дом'/ Bilding: int
    /'Корпус'/ BildingPart: int
    /'Комната'/ Room: str:int
    /'Индекс'/ Postcode: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Страны'/ entity Countries <<Ready>> {
    *Id: GUID
    --
    /'Код'/ *CodeISO: int
    /'Наименование'/ *Name: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Регионы'/ entity Regions <<Ready>> {
    *Id: GUID
    --
    /'Страна'/ *СountyId: GUID:Countries.Id
    /'Код'/ Code: int
    /'Наименование'/ *Name: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Районы'/ entity Districts <<Ready>> {
    *Id: GUID
    --
    /'Регион'/ *RegionId: GUID:Regions.Id
    /'Наименование'/ *Name: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Населенные пункты'/ entity Localities <<Ready>> {
    *Id: GUID
    --
    /'Регион'/ *RegionId: GUID:Regions.Id
    /'Район'/ DistrictId: GUID:Districts.Id
    /'Наименование'/ *Name: str:200
     --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Типы населенных пунктов'/ LocalitiesTypes: enum:enumvalue
    'enumvalue: 0|Индекс,10|Город,20|Поселок,21|Станица,30|Древня,31|Село,32|Хутор,40|Станция,41|ЖД станция
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Организации-участники торгов'/ entity Organizations <<Work>> {
    *Id: GUID
    --
    /'Код'/ *Code: str:50
    /'Код ЦБ'/*CodeCB: str:50
    /'Форма собственности'/ *OwnershipTypeId: GUID:OwnershipTypes.Id 
    /'Наименование'/ *Name: str:200
    /'Сокращенно наименование'/ *ShortName: str:50
    /'Полное наименование на иностранном языке'/ ForeignLanguageName: str:200
    /'Краткое наименование на иностранном языке'/ ForeignLanguageShortName: str:50
    /'Страна'/*CountryId: GUID:Countries.Id
    /'Страна'/ *CountryName: str:200:Countries.Name
    /'Юридический адрес'/ *LegalAddressId: GUID:Addresses.Id
    /'Почтовый адрес'/ *PostalAddressId: GUID:Addresses.Id
    /'ИНН'/ INN: str:50
    /'КИО'/ KIO: str:50
    /'КПП'/ KPP: str:50
    /'ОКПО'/ OKPO: str:50
    /'ОГРН'/ OGRN: str:50
    /'Дата присвоения ОГРН'/ OGRNDate: date
    /'Место выдачи ОГРН'/ OGRNPlace: str:200
    /'ОГРНИП'/ OGRNIP: str:50
    /'Дата регистрации ИП'/ OGRNIPDate: date
    /'Паспорт'/ Passport:str50
    /'ФИО руководителя'/ *CEOFullName: str:200
    /'ФИО руководителя в родительном падеже'/ *CEOFullNameGenetive: str:200
    /'Должность руководителя'/ *CEOPostName: str:200
    /'Должность руководителя в родительном падеже'/ *CEOPostNameGenetive: str:200
    /'Телефон'/ *Phone: str:50
    /'Е-мэйл'/ *Email: str:50
    /'Web-адрес'/ URL: str:50
    /'Вид деятельности по ОКВЭД'/ *OKVEDId: GUID:OKVED.Id
    /'Банк'/ *BankId: GUID:Banks.Id
    /'Расчетный счёт'/ *CheckingAccount: str:50
    /'???Аккредитация'/ *Accreditation: bool
    /'???Дата аккредитации'/ AccreditationDate: date 
    /'???Дата отмены аккредитации'/ CancellationDate: date 
    --
    /'Статус'/ *Status: GUID:OrganizationStatuses.Id
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Статус организации'/ entity OrganizationStatuses <<Ready>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Формы собственности'/  entity OwnershipTypes <<Ready>> {
    *Id: GUID
    --
    /'Полное наименование'/ *Name: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
} 

/'Банки'/ entity Banks <<Ready>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:200
    /'БИК'/ *BIK: str:50
    /'Адрес'/ *AddressId: GUID:Addresses.Id
    /'Корресподентский счёт'/ *CorrespondentAccount: str:50
    /'Телефон'/ *Phone: str:50
    /'Веб-адрес'/ URL: str:50
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Виды деятельности по ОКВЭД'/ entity OKVED <<Ready>> {
    *Id: GUID generated create
    --
    /'Код'/ *Code: str:50
    /'Наименование'/ *Name: str:200
    /'Расшифровка'/ *Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Документы'/ entity Documents <<Ready>> {
    *Id: GUID generated create
    --
    /'Организация'/ *OrganizationId: GUID:Organizations.Id
    /'Вид документа'/ *DocumentKindId: GUID:DocumentKinds.Id 
    /'Наименование документа'/ *Name: str:200
    /'Номер документа'/ *Name: str:50
    /'Дата документа'/ *Date: Date
    /'Тема документа'/ *Name: str:200
    /'Дата завердения действия'/ EndDate: Date
    --
    /'Сффлка на документ в файловом зранилище'/ *FileId: GUID
    /'Расширение файла'/ FileExtention str:50
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'Вид документа'/ entity DocumentKinds <<Ready>>{
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
    --
    /'Создано'/ *CreatedAt: DateTime
    /'Кем создано'/ *CreatedBy: GUID:Users.Id
    /'Модифицировано'/ LastModifiedAt: DateTime
    /'Кем модифицировано'/ LastModifiedBy: GUID:Users.Id
}

/'New 09/12/21'/

/'Каталог ТРУ'/
 entity Commodities <<Work>> { 
    *Id: GUID
    --
    /'Наименование товара'/ *Name:  GUID:CommoditiesNames.Id
    /'Краткое название'/ *ShortName: GUID:CommoditiesNames.Id
    /'??? Мнемоника'/ *Mnemonic: str:250
    /'Классификатор товаров'/ *CommoditiesClassifier: GUID:CommoditiesClassifier.Id
    /'Вид товара'/ *Kind: GUID:CommoditiesKind.Id
    /'Лот (единица измерения товара)'/ *BaseUnit: GUID:BaseUnits.Id
    /'Размер лота'/ Quantity: float: 
    /'Базис поставки'/ *Bases: GUID:Addresses.Id
    /'Завод-производитель'/ *Plant: GUID:Plants.Id
    /'Упаковка'/ *Package: GUID:Packaging.Id
    /'Описание товара'/ Description: str:200
    /'Продавец'/ OrganisationsCustomer: GUID:Organisations.Id
    /'Спецификация'/ *Specifications: GUID:Specifications.Id
    /'Сопроводительные документы'/ Files: bin
    --
    /'Статус'/ *Status: GUID:CommoditiesStatus.Id
    /'Дата изменения'/ ChangeDateTime: Date
    /'Дата создания'/ *CreateDateTime: Date
    /'Автор'/ *CreatedByUser: GUID:Users.Id
}

/'Наименование товара'/ entity CommoditiesNames <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:200
    /'Краткое название'/ *ShortName: str:200
    /'Классификатор товаров'/ *CommoditiesClassifier: GUID:CommoditiesClassifier.Id
    --
    /'Статус'/ *Status: GUID:CommoditiesStatu.Id
    /'Дата изменения'/ *ChangeDateTime: Date
    /'Дата создания'/ *CreateDateTime: Date
    /'Автор'/ *CreatedByUser: GUID:Users.Id
    /'Дата блокировки'/ *LockDate: Date
}

/'Спецификация биржевых товаров'/ entity Specifications <<Work>> {
    *Id: GUID
    --
    /'Номер'/ *Number: str:50
    /'Дата'/ *Date: Date
    /'Тип спецификации'/ *TypeSpecifications: GUID:TypeSpecifications.Id
    /'Участник торгов'/ *Organisation: GUID:Organisations.Id
    /'Перечень берживых товаров (табличная часть)'/ *SpecificationCommodities: GUID:SpecificationCommodities.Id
    --
    /'Статус'/ *Status: GUID:SpecificationStatus.Id
    /'Дата создания'/ *CreateDateTime: Date
    /'Автор'/ *CreatedByUser: GUID:Users.Id
    /'Дата утверждения'/ *ApprovalDate: Date
}

/'Перечень биржевых товаров в спецификации'/ entity SpecificationCommodities <<Work>>{
    *Id: GUID 
    --
    /'Наименование товара'/ *Name: GUID:CommoditiesNames.Id
    /'Краткое название'/ *ShortName: str:200
    /'Виды сопроводительных документов'/ DocumentsKinds: GUID:DocumentsKinds.Id
    // Specifications.Id для разработчиков
    --
    /'??? Мнемоника'/ *Mnemonic: str:200
    /'Вид товара'/ *Kind: GUID:CommoditiesKind.Id
    /'Классификатор товаров'/ *CommoditiesClassifier: GUID:CommoditiesClassifier.Id
    /'Лот (единица измерения товара)'/ *BaseUnit: GUID:BaseUnit.Id
    /'Размер лота'/ Quantity: str:50
    /'Описание товара'/ Description: str:200
}

'**Справочники

/'Статусы Каталога ТРУ'/ entity CommoditiesStatus <<Work>>{
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
}

/'Статус Cпецификации'/ entity SpecificationStatus <<Work>>{
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
    /'Описание'/ Description: str:200
}

/'Виды сопроводительных документов'/ entity DocumentsKinds <<Work>>{
    *Id: GUID
}

/'Категория товара'/ entity CommoditiesCategories <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:200
    /'Краткое название'/ *ShortName: str:50
}

/'Вид товара'/ entity CommoditiesKind <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:200
    /'Краткое название'/ *ShortName: str:50
}

/'Единица измерения'/ entity BaseUnits <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:200
    /'Краткое название'/ *ShortName: str:50
}

/'Завод-производитель'/ entity Plants <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str: 200
    /'Краткое название'/ *ShortName: str:50
}

/'Виды упаковок'/ entity PackagingTypes <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:200
    /'Краткое название'/ *ShortName: str:50
}

/'(Преработать) Классификатор товаров'/ entity CommoditiesClassifier <<Work>> {
    *Id: GUID
    --
    /'Тип записи'/ *Type: enum:section|Отделение,category|Категория,kond|Вид form
    /'Уровень родитель'/ *ParentLevel: GUID:CommoditiesClassifier.Id
    /'Код'/ Code str:50
    /'Краткое наименование'/ ShortName: str:50
    /'Полное наименование'/ Name: str:200
 }

/'Тип специификации'/ entity TypeSpecifications <<Work>> {
    *Id: GUID
    --
    /'Наименование'/ *Name: str:50
}
/'--------------------'/

'Пользователи
    Users::OrganizationId }|--|| Organizations::Id
    Users::RolesId }|--|| Roles::Id
    
'Разрешения'
    Permissions::RolesId }|--|{ Roles::Id

'Адреса
    Addresses::CountryId }|--|| Countries::Id
    Addresses::RegionId }|--|| Regions::Id
    Addresses::DistrictId }|--|| Districts::Id
    Addresses::LocalityId }|--|| Localities::Id

'Организация
    
    Organizations::OwnershipTypeId }|--|| OwnershipTypes::Id
    Organizations::BusinessLineId }|--|{ BusinessLines::Id
    Organizations::LegalAddressId }|--|| Addresses::Id
    Organizations::PostalAddressId }|--|| Addresses::Id
    Organizations::BankId }|--|| Banks::Id
    Organizations::OrganizationStatusId }|--|| OrganizationStatuses::Id

'Документация
    Documents::OrganizationId }|--|| Organizations::Id
    Documents::DocumentKindsId }|--|| DocumentKinds::Id

/'New 09/12/21'/
'Каталог ТРУ'
    Commodities::Name ||--|| CommoditiesNames::Id
    Commodities::Kind }|--|| CommoditiesKind::Id
    Commodities::BaseUnit }|--|| BaseUnits::Id
    Commodities::CommoditiesClassifier }|--|| CommoditiesClassifier::Id
    Commodities::Package ||--|| Packaging::Id
    Commodities::Plant }|--|| Plants::Id
    Commodities::OrganisationsCustomer }|--|| Organizations::Id
    Commodities::CatalogStatus }|--|| CommoditiesStatus::Id
    Commodities::Specifications ||--|| Specifications::Id 

'Спецификация биржевых товаров
    Specifications::Organisation }|--|| Organizations::Id
    Specifications::CommoditiesName }|--|| CommoditiesNames::Id
    Specifications::Сreator }|--|| Users::Id
    Specifications::SpecificationStatus }|--|| SpecificationStatus::Id
    Specifications::TypeSpecifications }|--|| TypeSpecifications::Id

'Перечень берживых товаров
    SpecificationCommodities::Name }|--|| CommoditiesNames::Id
    SpecificationCommodities::ShortName }|--|| CommoditiesNames::Id
    SpecificationCommodities::Kind }|--|| CommoditiesKind::Id
    SpecificationCommodities::CommoditiesClassifier }|--|| CommoditiesClassifier::Id
    SpecificationCommodities::BaseUnit }|--|| BaseUnits::Id
    SpecificationCommodities::DocumentsKinds }|--|| DocumentsKinds::Id

@enduml