@startuml "ЦТС.A1.1 Новый тариф (услуга)"
title "ЦТС.А1.1.1 Создание нового тарифа(услуги) в Каталоге услуг"
actor "Сотрудник ЦТС" as UserCTS
participant "Форма Каталог услуг" as СatalogService
database "База данных" as Database
participant "Сайт ЦТС" as SiteCTS
actor "Участник торгов" as User

autonumber

autonumber
UserCTS -> СatalogService: Открыть форму
activate UserCTS
activate СatalogService

СatalogService-->UserCTS: Система показывает форму Каталог услуг
deactivate UserCTS
deactivate СatalogService

loop Проверка и заполнение формы
 
    UserCTS->СatalogService: Заполняет Наименование тарифа (услуги)
    
    activate UserCTS
    activate СatalogService
    
    note right
    Заполняется автоматически при
    создании: Номер, Автор.
    end note

    UserCTS->СatalogService: Заполняет Вид тарифа (услуги)
    UserCTS->СatalogService: Основание оплаты
    UserCTS->СatalogService: Цена тарифа (услуги)
    UserCTS->СatalogService: Вид валюты
    UserCTS->СatalogService: ??? НДС

    UserCTS->СatalogService: Дата изменение тарифа (услуги)
    UserCTS->СatalogService: Дата вступления указанных изменений в силу

    СatalogService -> СatalogService: Проверка корректности заполненных данных 
    activate СatalogService
    deactivate СatalogService
    СatalogService --> UserCTS: Ошибка ввода данных! (Текст ошибки в разработке) 
 
    activate UserCTS
    UserCTS->СatalogService: Корректировка ранее введенных данных
    deactivate UserCTS
deactivate UserCTS
deactivate СatalogService
end

UserCTS->СatalogService: Нажимает на кнопку Сохранить
activate UserCTS
activate СatalogService
note right
    Заполняется автоматически 
    при сохранении записи: 
    Статус="Создано"
    (Пример. Текст статуса в разработке), 
    Дата создания.
end note

СatalogService->Database: Запись в базу данных
activate Database
СatalogService-->UserCTS: Выходит из формы Каталог услуг

deactivate UserCTS
deactivate СatalogService

Database->Database: Создание записи в базе данных

activate Database
deactivate Database

Database->SiteCTS:
Database->User:

@enduml