@startuml "ЦТС.А3.1 Допуск товара к торгам"
title "ЦТС.А3.1.6 Уведомление – Спецификация утверждена"
actor "Участник торгов" as User
participant "Коммуникационная панель" as CommunicationPanel

autonumber

activate User
User-->CommunicationPanel: Получено уведомление утверждении запроса, переход в блок уведомлений
activate CommunicationPanel

CommunicationPanel-->User: Открылись уведомления пользователя
deactivate CommunicationPanel

User-->User: Нажать на уведомление "Спецификация биржевых товаров утверждена"

@enduml