@startuml "ЦТС.А3.1 Допуск товара к торгам"
title "ЦТС.А3.1.2 Утверждение Спецификации на допуск товара к торгам"
actor "Менеджер торгов" as UserCTS
participant "Коммуникационная панель" as CommunicationPanel
boundary "Реестр Спецификаций" as Specification
participant "Каталоге ТРУ" as Communication
actor "Участник торгов" as User

autonumber

activate UserCTS
UserCTS->UserCTS: Получение запроса на согласование Спецификация биржевых товаров


UserCTS-->CommunicationPanel: Переход в блок "Визы" коммуникационной паанели
activate CommunicationPanel
CommunicationPanel-->UserCTS: Открылись объекты на визировании
deactivate CommunicationPanel
UserCTS-->UserCTS: Нажать на визу "Запрос на согласование Спецификация биржевых товаров"

note left
 auto: Открылся объект "Спецификация биржевых товаров"
end note 

UserCTS->UserCTS: Проверка корректно заполненных данных

        UserCTS-->CommunicationPanel: Нажать кнопку "Отклонить"
    note left
         manual: Заполнить поле Комментарий к визе
    end note
    activate CommunicationPanel

CommunicationPanel-->CommunicationPanel: Отображение уведомления об отклонении отправившему запрос

CommunicationPanel-->User: Переход к "А3.1.3 Уведомление – Спецификация отклонена"

UserCTS-->CommunicationPanel: Нажать на кнопку "Утвердить"
deactivate UserCTS
CommunicationPanel-->CommunicationPanel: Отображение уведомления об утверждении отправившему запрос
deactivate UserCTS
CommunicationPanel-->User: Смена статуса и добавление даты утверждения

CommunicationPanel->Specification: Переход к "А3.1.4 Создание в Каталоге ТРУ записей по утвержденной спецификации"
deactivate CommunicationPanel
activate Specification
Specification-->Specification: Сменить статус Спецификации
note left
    Сменить статус с
    "Отправлена на согласование"
    на "Отклонена/Утверждена"
end note
Specification-->Specification: Изменить "Дату утверждения"

Specification->Communication: Переход к "А3.1.4 Создание в Каталоге ТРУ записей по утвержденной спецификации"

@enduml