@startuml "ЦТС.А3.1 Допуск товара к торгам"
title "ЦТС.А3.1.10 Запрос на cогласование Спецификация биржевых товаров отклонен"
actor "Участник торгов" as User
participant "Коммуникационная панель" as CommunicationPanel

autonumber

activate User
User-->CommunicationPanel: Получено уведомление от утверждении запроса, переход в блок уведомлений

CommunicationPanel-->User: Открылись уведомления пользователя
User-->User: Нажать на уведомление "Спецификация биржевых товаров отклонена"

note left
  auto: Открылся комментарий к визе об отклонении A3.1.1
end note

@enduml