@startuml "ЦТС.А3.1 Допуск товара к торгам"
title "ЦТС.А3.1.4 Создание в Каталоге ТРУ записей по утвержденной спецификации"
participant "Реестр Спецификаций" as Specification
database "База данных" as Database
participant "Каталоге ТРУ" as Communication

autonumber

Specification->Database: Спецификации на снятие товара с торгов (Товары сняты с торгов)
activate Specification
deactivate Specification
activate Database

Database->Database: Создание записи в базе данных

Database->Communication: Изменение записи в Каталоге ТРУ записей по утвержденной спецификации
deactivate Database

activate Communication
note right
    Заполнение полей: 
    Статус: Товар снят с торгов. 
end note
Communication->Communication: Создание записей Каталоге ТРУ 
@enduml