@startuml "ЦТС.А3.3.2 Публикация новости о снятии товара с торгов
title "ЦТС.А3.3.4 Публикация новости о товаре снятом с торгов"
database "База данных" as DataBase
participant "Сайт ЦТС" as SiteCTS

autonumber

DataBase-->SiteCTS: Товары сняты с торгов
DataBase-->SiteCTS: Публикация новости о снятии товаров с торгов
/'Придумать текст новости???'/
 
@enduml