@startuml

title "ЦТС.А2.1.3.Подтверждение регистрации по Е-мэйл"

'boundary "Форма для предварительной регистрации" as PreRegistrationForm
entity "Система" as System
entity "Е-мэйл" as Email
actor "Участник Торгов" as User


autonumber

System->Email:Система высылает на Емэйл письмо для подтверждении регситрации
activate System
activate Email
deactivate System

User ->Email:Входит в почту
activate User
Email-->User:Отображение почты
deactivate Email

User->Email:Нажимает кнопку "Авторизоваться"

activate Email
deactivate User

Email->System:Переход в А2.1.4 Подтверждение регистрации
activate System

@enduml