@startuml
/'Название файла будет: ЦТС.<Номер схемы БП>.<Номер этапа>.<Название этапа в схеме БП>'/
title "ЦТС.А2.1.1.Регистрация пользователя"
actor "Участник Торгов" as User
boundary "Форма для предварительной регистрации" as PreRegistrationForm
entity "Система" as System

autonumber

User -> PreRegistrationForm: Открыть форму
activate User
activate PreRegistrationForm

PreRegistrationForm-->User: Система показывает форму регистрации
deactivate User
deactivate PreRegistrationForm

loop Проверка и заполнение формы
User -> PreRegistrationForm: Ввести данные ФИО, Корп. e-mai, Телефон, ИНН, Пароль, Подтв. пароля
activate User
activate PreRegistrationForm

User -> PreRegistrationForm: Нажать кнопку "Зарегистрироваться"
PreRegistrationForm -> PreRegistrationForm: Проверка корректности заполненных данных 
activate PreRegistrationForm
deactivate User
deactivate PreRegistrationForm

 alt "Если данные введены некорректно"

 PreRegistrationForm --> User: Ошибка ввода данных! (Текст ошибки в разработке) 
 activate PreRegistrationForm
 activate User
 deactivate PreRegistrationForm

 User->PreRegistrationForm: Корректировка ранее введенных данных
 deactivate User
 deactivate PreRegistrationForm
 
 else "Если данные  введены корректно"

 PreRegistrationForm -> System: Переход к А2.1.2
 activate PreRegistrationForm
 activate System
 deactivate PreRegistrationForm

 end
end
@enduml


